sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_c225111d5ba6_key -iv $encrypted_c225111d5ba6_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- ./sfdx/install
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core

jobs:
  include:
  if: branch =~ ^feature.* 
  - staget: test
  script:
    - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
      --username $USERNAME --setdefaultdevhubusername -a HubOrg
    - sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
      --wait 2
    - sfdx force:org:display -u ciorg
    - sfdx force:source:push -u ciorg
    - sfdx force:apex:test:run -u ciorg --wait 10
    - sfdx force:org:delete -u ciorg -p

jobs:
  include:
    if: branch = master
    - stage: deploy
    script:
      - sfdx force:auth:jwt:grant --clientid $devkey --jwtkeyfile assets/server.key
        --username $devun -a DevOrg
      - mkdir mdapioutput
      - sfdx force:source:convert -d mdapioutput/
      - sfdx force:mdapi:deploy -d mdapioutput/ -u DevOrg -w 100
      - sfdx force:org:display -u DevOrg
      - sfdx force:apex:test:run -u DevOrg --wait 10
      - sfdx force:auth:logout -u DevOrg -p
